apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: data
  labels:
    app: mysql-pod
    tier: data

spec:
  containers:
  - name: mysql-container
    image: mysql:5
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: lab