apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-mysql
  namespace: data
  labels:
    app: database
    type: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        tier: data
    spec:
      containers:
      - name: mysql-container
        image: mysql:5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: lab

   